admin:
  realm: master
  username: grigolenok
  password: 2661617Egor
  resource: admin-cli
server:
  port: 8081
keycloak:
  realm: mBank
  resource: mBankAuthorization
  bearer-only: true
  credentials:
    secret: 7ML2OYtwAoxZ1xu9ePCKQZBKIx5Higf5
  use-resource-role-mappings: true
  auth-server-url: http://localhost:8080/auth
spring:
  main:
    allow-circular-references: true
