server:
  port: 8081
keycloak:
  realm: mBank
  resource: mBankAuthorization
  bearer-only: true
  credentials:
     secret: M15X3Tlhi0lG4CSANBH2wRmnaZueo0AJ
  auth-server-url: http://localhost:8080/auth
spring:
  main:
    allow-circular-references: true
